use crate::{
    AppPanel, AppTab, ConfirmRequest, DbNav, DiffMode, FindTarget, FindWidgetToggle,
    InputModifiers, LocationSnapshot, MatchHit, NavCandidatesPopup, NavPendingJump, PickerInput,
    SearchTarget, SearchViewport, SshTarget, TextEditOp, Toast, ViewMode,
};
use reef_core::diff::DiffLayout;
use reef_core::git::GraphScope;
use reef_core::hosts::HostEntry;
use reef_core::nav::{LspBadge, NavLang};
use reef_core::prefs::ThemePref;
use reef_core::preview::PreviewDocument;
use std::path::PathBuf;
use std::sync::Arc;
use std::time::Instant;

#[derive(Debug, Clone)]
pub enum AppCommand {
    Quit,
    OpenHelp,
    CloseHelp,
    OpenSettings,
    CloseSettings,
    SetSettingsPrefCache {
        theme_pref: ThemePref,
        editor_command: String,
    },
    MoveSettingsSelection(i32),
    SelectSettingsRow(usize),
    BeginSettingsEditorCommandEdit,
    CommitSettingsEditorCommandEdit,
    CancelSettingsEditorCommandEdit,
    EditSettingsEditorCommand(TextEditOp),
    PasteSettingsEditorCommand(String),
    CloseActivePalettes,
    SetActiveTab(AppTab),
    SetActivePanel(AppPanel),
    SetViewMode(ViewMode),
    ToggleSidebar,
    EnterFocusedPreview {
        uses_three_col: bool,
    },
    ToggleFocusedPreview {
        uses_three_col: bool,
    },
    EnterFocusedPreviewWithFile {
        rel: PathBuf,
        dark: bool,
        wants_decoded_image: bool,
    },
    ToggleDiffLayout,
    CyclePanel {
        reverse: bool,
        uses_three_col: bool,
    },
    NormalizeActivePanel {
        uses_three_col: bool,
    },
    SetDiffLayout(DiffLayout),
    SetDiffMode(DiffMode),
    LoadDiff {
        dark: bool,
    },
    SetPreviewVerticalScroll(usize),
    ClampPreviewVerticalScroll(usize),
    CenterPreviewOnLine {
        line: usize,
        view_height: usize,
    },
    SetPreviewHorizontalScroll(usize),
    ClampPreviewHorizontalScroll(usize),
    SetDiffVerticalScroll(usize),
    SetDiffHorizontalScroll(usize),
    SetDiffScrollState {
        scroll: usize,
        h_scroll: usize,
        sbs_left_h_scroll: usize,
        sbs_right_h_scroll: usize,
    },
    SetActiveDiffVerticalScroll(usize),
    SetCommitFileDiffScrollState {
        scroll: usize,
        h_scroll: usize,
        sbs_left_h_scroll: usize,
        sbs_right_h_scroll: usize,
    },
    CommitReplaceInFiles,
    RefreshStatus,
    RefreshFileTree,
    RefreshFileTreeWithTarget(Option<PathBuf>),
    RevealFileTreePath(PathBuf),
    SelectFileTreeEntry(usize),
    NavigateFileTree(i32),
    NavigateGitFiles(i32),
    ScrollFileTree(i32),
    ReconcileFileTreeScroll {
        visible_rows: usize,
        selection_changed: bool,
    },
    ToggleFileTreeExpand(usize),
    ActivateFileTreeEntryAtIndex(usize),
    ActivateSelectedFileTreeEntry,
    RequestEditSelectedFileTreeEntry,
    RequestEditSelectedGitFile,
    ClearFileTreeSelectionAndEdit,
    ToggleCurrentFileSelection,
    ClearFileSelection,
    ExtendFileSelectionAfterTreeNav(i32),
    ToggleFileSelectionAtIndex(usize),
    LoadSelectedPreview,
    LoadPreview(PathBuf),
    ReloadPreviewNow {
        dark: bool,
        wants_decoded_image: bool,
    },
    ApplyPreviewResult {
        generation: u64,
        result: Result<Option<PreviewDocument>, String>,
        preview_view_h: usize,
    },
    PreviewScroll(i32),
    PreviewHorizontalScroll(i32),
    DiffScroll(i32),
    DiffHorizontalScroll(i32),
    ScrollCommitDetailVertical(i32),
    SetCommitDetailVerticalScroll(usize),
    ClampCommitDetailVerticalScroll(usize),
    ClampCommitDetailDiffHorizontalScroll(usize),
    ClampCommitDetailSbsHorizontalScrolls {
        left: usize,
        right: usize,
    },
    ScrollCommitDetailFileDiffVertical(i32),
    SetCommitDetailFileDiffVerticalScroll(usize),
    OpenDbGoto,
    CloseDbGoto,
    DbNavigate(DbNav),
    DbToggleSchema(String),
    DbSelectObject(reef_sqlite_preview::DbObjectKey),
    DbNavigateToPage(u64),
    EditDbGoto(TextEditOp),
    PasteDbGoto(String),
    ConfirmDbGoto,
    HorizontalScrollAtColumn {
        column: u16,
        total_width: u16,
        delta: i32,
    },
    OpenQuickOpen,
    CloseQuickOpen,
    ApplyQuickOpenPickerInput {
        input: PickerInput,
        visible_rows: usize,
    },
    MoveQuickOpenSelection {
        delta: i32,
        visible_rows: usize,
    },
    SelectQuickOpenMatch {
        idx: usize,
        visible_rows: usize,
    },
    PasteQuickOpen(String),
    AcceptQuickOpenSelection {
        mru_cap: usize,
    },
    OpenGlobalSearch {
        seed: Option<String>,
    },
    CloseGlobalSearch,
    OpenGlobalReplaceTab,
    PinGlobalSearchToTab,
    AcceptGlobalSearchHit(MatchHit),
    BeginVimSearch {
        target: SearchTarget,
        backwards: bool,
    },
    ConfirmVimSearch,
    CancelVimSearch {
        dark: bool,
    },
    EditVimSearchInput(TextEditOp),
    PasteVimSearchInput(String),
    RecomputeVimSearch {
        rows: Vec<String>,
        dark: bool,
        viewport: SearchViewport,
    },
    StepVimSearch {
        reverse: bool,
        dark: bool,
        viewport: SearchViewport,
    },
    ClearVimSearch,
    ClearVimSearchIfTarget(SearchTarget),
    BeginFindWidget {
        target: FindTarget,
        query: String,
    },
    CloseFindWidget {
        dark: bool,
    },
    EditFindWidgetInput(TextEditOp),
    PasteFindWidgetInput(String),
    ToggleFindWidgetOption(FindWidgetToggle),
    RecomputeFindWidget {
        rows: Vec<String>,
        dark: bool,
        viewport: SearchViewport,
    },
    StepFindWidget {
        reverse: bool,
        viewport: SearchViewport,
    },
    MoveGlobalSearchSelection {
        delta: i32,
        visible_rows: usize,
    },
    ApplyGlobalSearchPickerInput {
        input: PickerInput,
        now: Instant,
        visible_rows: usize,
    },
    PasteGlobalSearchOverlay {
        text: String,
        now: Instant,
    },
    PasteGlobalSearchTab {
        text: String,
        now: Instant,
    },
    ReloadGlobalSearch {
        now: Instant,
    },
    ScheduleGlobalSearchPreviewSync {
        now: Instant,
    },
    ClearGlobalSearchPreviewSync,
    DrainGlobalSearchPreviewSyncDebounce {
        now: Instant,
    },
    SyncGlobalSearchPreviewToSelected,
    FocusGlobalSearchFindInput,
    FocusGlobalSearchReplaceInput,
    FocusGlobalSearchList,
    CycleGlobalSearchFocusForward,
    CycleGlobalSearchFocusBackward,
    ToggleGlobalSearchReplace,
    ToggleGlobalSearchReplaceForSearchTab,
    ToggleGlobalSearchMatchExcluded(usize),
    SelectGlobalSearchResult {
        idx: usize,
        visible_rows: usize,
    },
    ScrollGlobalSearchResultsHorizontal(i32),
    SetGlobalSearchResultsHorizontalScroll(usize),
    EditGlobalSearchFindInput {
        op: TextEditOp,
        now: Instant,
    },
    EditGlobalSearchReplaceInput(TextEditOp),
    SetGraphScope(GraphScope),
    SetSplitPercent(u16),
    SetGraphDiffSplitPercent(u16),
    SetCtrlHoverTarget(Option<(usize, std::ops::Range<usize>)>),
    PushToast(Toast),
    RefreshGraph,
    RefreshGraphUncached,
    LoadCommitDetail,
    LoadCommitRangeDetail,
    ReloadGraphSelection,
    LoadCommitFileDiff {
        path: String,
        dark: bool,
        uses_three_col: bool,
    },
    ReloadCommitFileDiff {
        dark: bool,
        uses_three_col: bool,
    },
    ScrollGraphVertical(i32),
    ReconcileGraphScroll {
        visible_rows: usize,
        selection_changed: bool,
    },
    MoveGraphSelection(i32),
    SelectGraphCommit(String),
    FocusGraphCommit(String),
    ExtendGraphSelection(i32),
    ClearGraphRange,
    ResetGraphVisualAnchor,
    SetCommitEditing(bool),
    EditCommitMessage(TextEditOp),
    ToggleDiffMode {
        dark: bool,
    },
    ToggleStatusTreeMode,
    ToggleCommitDiffLayout,
    ToggleCommitDiffMode,
    ToggleCommitFilesTreeMode,
    ToggleCommitFilesDirCollapsed(String),
    ScrollGitStatusVertical(i32),
    ClampGitStatusScroll(usize),
    SelectGitFile {
        path: String,
        is_staged: bool,
        dark: bool,
    },
    SelectGitFileForDiscard {
        path: String,
        is_staged: bool,
        dark: bool,
    },
    StageFile {
        path: String,
        dark: bool,
    },
    UnstageFile {
        path: String,
        dark: bool,
    },
    StageAll {
        dark: bool,
    },
    UnstageAll {
        dark: bool,
    },
    StageFolder {
        path: String,
        dark: bool,
    },
    UnstageFolder {
        path: String,
        dark: bool,
    },
    ConfirmDiscard {
        dark: bool,
    },
    RunCommit,
    RunPush {
        force: bool,
    },
    ToggleStagedSection,
    ToggleUnstagedSection,
    ToggleGitStatusDir {
        is_staged: bool,
        path: String,
    },
    PromptDiscardFile {
        is_staged: bool,
        path: String,
    },
    PromptDiscardFolder {
        is_staged: bool,
        path: String,
    },
    PromptDiscardSection {
        is_staged: bool,
    },
    CancelGitConfirmations,
    DismissPushError,
    PromptPush {
        force: bool,
    },
    ConfirmPush {
        force: bool,
    },
    DismissCommitError,
    OpenHostsPicker {
        hosts: Vec<HostEntry>,
        recent: Vec<SshTarget>,
    },
    CloseHostsPicker,
    EnterHostsPickerPathMode,
    ReturnHostsPickerToSearchMode,
    ApplyHostsPickerSearchInput(PickerInput),
    EditHostsPickerPathInput(TextEditOp),
    ConfirmHostsPicker,
    PasteHostsPicker(String),
    SelectHostsPickerRow(usize),
    MoveHostsPickerSelection(i32),
    OpenGraphBranchPicker,
    CloseGraphBranchPicker,
    ApplyGraphBranchPickerInput {
        input: PickerInput,
        visible_rows: usize,
    },
    ConfirmGraphBranchPicker,
    PasteGraphBranchPicker(String),
    SelectGraphBranchPickerRow {
        idx: usize,
        visible_rows: usize,
    },
    MoveGraphBranchPickerSelection {
        delta: i32,
        visible_rows: usize,
    },
    ClearPreviewHighlight,
    SetPreviewHighlight {
        path: PathBuf,
        row: usize,
        byte_range: std::ops::Range<usize>,
        fade: crate::HighlightFade,
    },
    SetPreviewHighlightPendingUtf16(Option<std::ops::Range<u32>>),
    ResolvePreviewHighlightByteRange(std::ops::Range<usize>),
    StartPreviewHighlightCounting(Instant),
    RestorePreviewScrollAndClearHighlight(LocationSnapshot),
    ApplyLspStateChange {
        lang: NavLang,
        state: LspBadge,
    },
    RefreshLspInstalled,
    OpenNavCandidates(NavCandidatesPopup),
    SetNavPendingLspJump(NavPendingJump),
    SelectNavCandidate(usize),
    CloseNavCandidates,
    MoveNavCandidatesSelection(i32),
    ScrollNavCandidates(i32),
    PushLocationHistory(LocationSnapshot),
    JumpToLocation {
        target: LocationSnapshot,
        dark: bool,
        uses_three_col: bool,
    },
    LocationBack {
        current: Option<LocationSnapshot>,
        dark: bool,
        uses_three_col: bool,
    },
    LocationForward {
        current: Option<LocationSnapshot>,
        dark: bool,
        uses_three_col: bool,
    },
    NextNavRefineGeneration,
    DispatchLspRefineDefinition {
        generation: u64,
        lang: NavLang,
        cache_key: String,
        workspace_root: PathBuf,
        abs_file: PathBuf,
        source: Arc<[u8]>,
        line: u32,
        utf16_col: u32,
    },
    DispatchNavWorkspaceBuild,
    OpenFocusedPreviewFiles,
    CloseFocusedPreviewFiles,
    ToggleFocusedPreviewFiles,
    MoveFocusedPreviewFilesSelection(i32),
    SetFocusedPreviewFilesSelection(usize),
    ConfirmFocusedPreviewFilesSelection {
        dark: bool,
        uses_three_col: bool,
    },
    PickFocusedPreviewFile {
        idx: usize,
        dark: bool,
        uses_three_col: bool,
    },
    CloseFocusedPreview,
    NavigateTreeContextMenu(i32),
    OpenTreeContextMenu {
        target_entry_idx: Option<usize>,
        anchor: (u16, u16),
    },
    CloseTreeContextMenu,
    RequestTreeDeleteConfirm {
        path: PathBuf,
        is_dir: bool,
        hard: bool,
    },
    ExecuteTreeDelete(crate::TreeDeleteConfirm),
    RequestConfirm(ConfirmRequest),
    DismissConfirm,
    MarkCut(Vec<PathBuf>),
    MarkCopy(Vec<PathBuf>),
    ClearClipboard,
    PasteInto(PathBuf),
    DuplicateSelection,
    DuplicatePaths(Vec<PathBuf>),
    ResolvePasteConflict {
        resolution: reef_core::file_ops::Resolution,
        apply_to_all: bool,
    },
    CancelPasteConflict,
    BeginTreeDrag {
        sources: Vec<PathBuf>,
        mods: InputModifiers,
    },
    DropTreeDrag {
        release_mods: InputModifiers,
    },
    ArmFileTreeDragPress {
        idx: usize,
        col: u16,
        row: u16,
        mods: InputModifiers,
    },
    AutoExpandTreeDragHover {
        now: Instant,
    },
    UpdateTreeDragHover(Option<usize>),
    UpdateTreeDragModifiers(InputModifiers),
    CancelTreeDrag,
    EnterPlaceMode(Vec<PathBuf>),
    ExitPlaceMode,
    RequestFileCopy {
        sources: Vec<PathBuf>,
        dest_dir: PathBuf,
    },
    UpdatePlaceModeHover(Option<usize>),
    AutoExpandPlaceModeHover {
        now: Instant,
    },
    CommitTreeEdit,
    CancelTreeEdit,
    EditTreeEditInput(TextEditOp),
    PasteTreeEdit(String),
    BeginTreeEdit {
        mode: crate::features::tree_edit::TreeEditMode,
        parent_dir: PathBuf,
        rename_target: Option<PathBuf>,
        anchor_idx: Option<usize>,
    },
    CollapseAllTreeEntries,
    ExtendFileSelectionToIndex(usize),
    PasteCommitMessage(String),
    CopyToClipboard {
        text: String,
        success: Option<Toast>,
        failure: Toast,
    },
    OpenUrl(String),
}
