//! Build script — materialises compile-time constants for the agent
//! auto-deployment path.
//!
//! At compile time we try to locate a matching `reef-agent` binary on disk
//! and `include_bytes!` it into the main `reef` binary. When the agent is
//! later pushed to a host that has no external network (or the GitHub
//! release download fails) we fall back to streaming this embedded copy
//! over ssh via `cat >`. See `src/agent_deploy/upload.rs`.
//!
//! The embed is best-effort:
//!   - On a `cargo build -p reef` where `target/{profile}/reef-agent`
//!     doesn't exist yet (typical first build), we embed an empty slice
//!     and the fallback simply surfaces `NoEmbeddedBinaryForArch`.
//!   - Only the host arch of the machine doing the build is embedded — a
//!     true multi-arch release ships multiple `reef` binaries via CI,
//!     each with its own matching agent. Cross-arch deployment targets
//!     rely on the GitHub Release download path (primary).
//!
//! Emits: `$OUT_DIR/embedded_agent.rs` with three constants:
//!   `EMBEDDED_AGENT_PLATFORM: &str`
//!   `EMBEDDED_AGENT_ARCH: &str`
//!   `EMBEDDED_AGENT_BYTES: &[u8]`

use std::env;
use std::path::{Path, PathBuf};

fn main() {
    let out_dir = env::var_os("OUT_DIR").expect("OUT_DIR set by cargo");
    let out_path = PathBuf::from(&out_dir).join("embedded_agent.rs");

    let target = env::var("TARGET").unwrap_or_default();
    let (platform, arch) = parse_target(&target);

    // Look for the agent next to ourselves. `OUT_DIR` lives under
    // `target/<profile>/build/<crate>-<hash>/out`; walk up three levels
    // to find `target/<profile>/`.
    let profile_dir = Path::new(&out_dir)
        .ancestors()
        .nth(3)
        .map(Path::to_path_buf);
    let agent_path = profile_dir.as_ref().map(|p| p.join("reef-agent"));

    let (agent_repr, had_bytes) = match agent_path.as_ref().filter(|p| p.is_file()) {
        Some(p) => {
            let escaped = p.display().to_string();
            // Use `include_bytes!` with a literal path so cargo's dep tracking
            // picks up changes to the file when it's rebuilt.
            println!("cargo:rerun-if-changed={escaped}");
            (format!("include_bytes!({:?}).as_slice()", p), true)
        }
        None => ("&[] as &[u8]".to_string(), false),
    };

    // Re-run when any of these env vars change, so switching `cargo build`
    // between arches or host triples regenerates the file.
    println!("cargo:rerun-if-env-changed=TARGET");
    println!("cargo:rerun-if-env-changed=REEF_EMBEDDED_AGENT");

    let contents = format!(
        "// Generated by build.rs — do not edit.\n\
         pub const EMBEDDED_AGENT_PLATFORM: &str = {platform:?};\n\
         pub const EMBEDDED_AGENT_ARCH: &str = {arch:?};\n\
         pub const EMBEDDED_AGENT_BYTES: &[u8] = {agent_repr};\n\
         pub const EMBEDDED_AGENT_PRESENT: bool = {had_bytes};\n",
    );

    std::fs::write(&out_path, contents).expect("write embedded_agent.rs");

    if !had_bytes {
        // Informational only — not a warning, so `-D warnings` users are
        // unaffected and first-time builds succeed.
        println!(
            "cargo:warning=reef-agent binary not found under target/{{debug,release}}/; \
             `reef --ssh` upload fallback will refuse to run until `cargo build -p reef-agent` \
             is done first."
        );
    }
}

/// Map a rustc target triple to the (platform, arch) labels VSCode-style
/// install scripts use (`linux/darwin/freebsd` × `x64/arm64/armhf/...`).
fn parse_target(triple: &str) -> (&'static str, &'static str) {
    let platform = if triple.contains("linux") {
        "linux"
    } else if triple.contains("darwin") || triple.contains("apple") {
        "darwin"
    } else if triple.contains("freebsd") {
        "freebsd"
    } else if triple.contains("windows") {
        "windows"
    } else {
        "unknown"
    };

    let arch = if triple.starts_with("x86_64") || triple.starts_with("amd64") {
        "x64"
    } else if triple.starts_with("aarch64") || triple.starts_with("arm64") {
        "arm64"
    } else if triple.starts_with("armv7") || triple.starts_with("armv8") {
        "armhf"
    } else if triple.starts_with("powerpc64le") || triple.starts_with("ppc64le") {
        "ppc64le"
    } else if triple.starts_with("riscv64") {
        "riscv64"
    } else if triple.starts_with("s390x") {
        "s390x"
    } else {
        "unknown"
    };

    (platform, arch)
}
