//! Compile-time embedded `reef-agent` binary.
//!
//! Generated by `build.rs`; see that file for the layout. The constants
//! here are `pub` so the deploy layer (`upload.rs`) can stream them over
//! an ssh pipe when the primary GitHub Release download path fails.

include!(concat!(env!("OUT_DIR"), "/embedded_agent.rs"));
